### ISSUE TITLE
Unsure if I did this right...

### ISSUE THREAD

**Issue by lunulae** [ForeverAndEverTeam/fae-mod#10]
I tried to do some proofreading and typo edits, I'm unsure if I published them correctly.
Sorry for the confusion if I put them in the wrong place, I'm still learning Github right now. ^_^;

**Comment by lunulae** [comment]
Hello! Sorry for the pestering, but I wanted to make sure my changes were received. It's okay if they aren't going to be implemented soon (or at all) but I wanted to make sure they got through.

**Comment by Saiv46** [comment]
Did you send changes directly to @AlexanDDOS, or over Github?

**Comment by AlexanDDOS** [comment]
I don't see your pull request. Can you make it or send me the edited files directly to me (via email)?

**Comment by lunulae** [comment]
Sorry about the late reply! I don't think I made the pull request correctly, but I have the links to the changed files I made [here](https://github.com/lunulae/fae-mod/blob/patch-1/game/topics.rpy) and [here](https://github.com/lunulae/fae-mod/blob/patch-2/game/greetings.rpy). 

Again, so sorry about the inconvenience. I hope it won't be too hard to mesh them with the current version.

**Comment by AlexanDDOS** [comment]
Sorry, but I do not see your pull request. Plus, I recommend you now not to change the file topics.rpy since I haven't finished with moving new topics from a proofread file. I'll notify you when I have done it.

**Comment by AlexanDDOS** [comment]
Well, I've added all the new topics, so you can make your pull request again, dealing with the file changes.

**Comment by TRIDENT1313** [comment]
[Closing as answered (and outdated as fuck)]
