### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by AGSans247** [ForeverAndEverTeam/fae-mod#101]
I booted up everything and it shows that a list index is out of range. I'm pretty sure something's in the /game directory that doesn't exist in the /dialogs folder. I tried to figure ways to fix it, but the code was unable to be decrypted on my end, and mainly out of pure respect for the devs' work. I don't know if it's something with the mod or something on my end, but I really think it should be checked out. This also may have something to do with the act that I closed to game on Sayori twice, for experimental purposes. 😅😅😅😅 
![Corrupted](https://user-images.githubusercontent.com/127927807/226045703-3323878f-2fdf-46cf-8550-7cd7e640263e.png)

**Comment by AGSans247** [comment]
P.S.: This also may have something to  do with the act that I closed to game on Sayori twice, for experimental purposes. 😅😅😅😅

**Comment by AGSans247** [comment]
P.S.: This also may have something to  do with the act that I closed to game on Sayori twice, for experimental purposes. 😅😅😅😅

**Comment by TRIDENT1313** [comment]
This has been noted, and will be fixed in a coming update
