### ISSUE TITLE
Unable to play/open the game at all bug

### ISSUE THREAD

**Issue by Someone257229** [ForeverAndEverTeam/fae-mod#102]
I wanted to see what happens when you close the game without saying goodbye and once I tried that it said "a expetion occured" text file popped up. I have tried reinstalling the game severall times but nothing seems to work. I also tried deleting the presistend but that didnt seem to do anything either. If anyone else has experienced this any help is appreciated! Thank you

**Comment by AGSans247** [comment]
The same thing happened to me. I even tried to see if I could fix the code myself, but sadly to no avail. 😑😑😑😑

**Comment by TRIDENT1313** [comment]
Been fixed in upcoming update.
