### ISSUE TITLE
The mod wont open at all

### ISSUE THREAD

**Issue by Tactie** [ForeverAndEverTeam/fae-mod#106]
I've actually followed the installation instructions, done everything I could possibly do but nothing works, when I try to open it, it just loads for a bit and then stops.

**Comment by TRIDENT1313** [comment]
Please ensure you're running the Forever&Ever.exe and not ddlc.exe.

**Comment by Tactie** [comment]
I did actually, and I just noticed that the scripts.rpa file doesn't exist in the installation so I can delete it.
