### ISSUE TITLE
Not able to import DDLC saves

### ISSUE THREAD

**Issue by iceypotato** [ForeverAndEverTeam/fae-mod#107]
Hi, when I first started the game, I tried to import my saves using the "Import DDLC Save" button, but it just results in an error in the game saying that it's corrupted or something. I don't know if this was a bug or not, but definitely seems so.

On another random note, how would you reset your progress in this game?

**Comment by TRIDENT1313** [comment]
Importing DDLC saves isn't easy.
Add in the differing ren'py vesions, and it becomes twice as difficult as changes to persistent encryption are made.

As for resetting progress...
I have to ask...
_Why_ do you want to reset?

**Comment by iceypotato** [comment]
> Importing DDLC saves isn't easy. Add in the differing ren'py vesions, and it becomes twice as difficult as changes to persistent encryption are made.

Oh, I see. Should an "Import Save" even be there if it doesn't work? Or, is it still being figured out?

> As for resetting progress... I have to ask... _Why_ do you want to reset?

Well, I thought that my persistent file was corrupted when I tried to import the saves, so I wanted to reset it. 
Anyways, even if I didn't have a good reason to reset, I would like to at least know how.

**Comment by TRIDENT1313** [comment]
We intend to make an import ddlc thing eventually, but for the moment it's been removed in upcoming update.

> Anyways, even if I didn't have a good reason to reset, I would like to at least know how.
It's in the same place all DDLC persistents go
Ren'Py folder in appdata.
