### ISSUE TITLE
Two questions

### ISSUE THREAD

**Issue by MonikaEndDie** [ForeverAndEverTeam/fae-mod#108]
Hello, so i have two things who worry me, one of them more than the other:

First, two day ago, for the first time, i've the pleasure of having Sayori asking me for a goodnight kiss, but the day after, my persistant got corrupted and now her affection, compliments, music and games option are reset! However, the topics and affection cap were not affected (i've also managed to get the music and games back with the topic talking about them). Is this bug will be fixed in a futute update?

and second: Sayori kept her scarf since new year event. Is she supposed to remove it at some point?

**Comment by TRIDENT1313** [comment]
First: Yes, it was a bug.
A product of hasty testing and hasty hotfixing that I didn't do properly.
It's been dealt with already.

Second:
Again, a bug that has been noted and fixed in upcoming update.

[Closing as resolved]
