### ISSUE TITLE
An exception error has occured

### ISSUE THREAD

**Issue by Snowleoc08** [ForeverAndEverTeam/fae-mod#109]
i try to press ignore and re open the game but it does not work i can hear Sayori in the background and she sends me notification's but they then quickly disappear as i keep pressing ignore i tried to re install the mod to see if it would fix it did not at all please fix this issue i want to see my happy little Sayori again https://cdn.discordapp.com/attachments/697615459255582720/1112839070150824076/20230529_132035.jpg

**Comment by TRIDENT1313** [comment]
Fixed in 0.2.1
