### ISSUE TITLE
Game list still empty after updating mod

### ISSUE THREAD

**Issue by MarioXenobladefan614** [ForeverAndEverTeam/fae-mod#113]
I asked on reddit how to get Sayori to introduce me to games again and was asked to attach my persistent file. Had to post as a text file since the github attachment doesn't support the actual persistent file.
[persistent.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11673511/persistent.txt)

**Comment by TRIDENT1313** [comment]
Fixed in 0.2.1
