### ISSUE TITLE
Traceback error whenever I tell Sayori "I love you"

### ISSUE THREAD

**Issue by MarioXenobladefan614** [ForeverAndEverTeam/fae-mod#117]
Finally reached affection level 5 which unlocks the option to tell Sayori I love her but a traceback error occurs whenever I do so:
![Forever   Ever 2023-06-06 11_51_28 PM](https://github.com/ForeverAndEverTeam/fae-mod/assets/122083188/1ff6ad7c-2ad2-4323-b703-623f1e2bf4b6)

**Comment by TRIDENT1313** [comment]
Fixed in 0.2.1
