### ISSUE TITLE
Another "I love you" Traceback error, and Reversi error

### ISSUE THREAD

**Issue by Amazingpotato917** [ForeverAndEverTeam/fae-mod#119]
Sorry for so many issues- But this appears when I say I love you to Sayori and try to play Reversi with Sayori (I am on the new version)
![Screenshot (60)](https://github.com/ForeverAndEverTeam/fae-mod/assets/92829097/837652d7-125a-45ee-8f26-be401f54ce20)
![Screenshot (61)](https://github.com/ForeverAndEverTeam/fae-mod/assets/92829097/f491c3c4-a060-4689-8c13-98a02479c1a7)

**Comment by TRIDENT1313** [comment]
Noted
I'm unsure how I missed this, but I did
I've pulled V0.2.1 for now, and will rebuild after fixing

**Comment by Amazingpotato917** [comment]
Okay, good luck with everything ^^

**Comment by TRIDENT1313** [comment]
Has been fixed
Minigames will not be fixed until sometime later
