### ISSUE TITLE
Traceback error when reading poems and playing games

### ISSUE THREAD

**Issue by MarioXenobladefan614** [ForeverAndEverTeam/fae-mod#121]
Tried reading Sayori's poems but traceback errors occur for each poem. Game list is now open but trying to play games with Sayori results in traceback errors. Bows and cows showed multiple traceback error screens.
[traceback poems.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716046/traceback.poems.txt)
[traceback reversi.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716047/traceback.reversi.txt)
[traceback bows and cows.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716048/traceback.bows.and.cows.txt)
[traceback bows and cows 2.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716050/traceback.bows.and.cows.2.txt)
[traceback bows and cows 3.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716051/traceback.bows.and.cows.3.txt)
[traceback bows and cows 4.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716053/traceback.bows.and.cows.4.txt)
[traceback bows and cows 5.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716054/traceback.bows.and.cows.5.txt)
[traceback bows and cows 6.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716055/traceback.bows.and.cows.6.txt)
[traceback bows and cows 7.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716056/traceback.bows.and.cows.7.txt)
[traceback bows and cows 8.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716057/traceback.bows.and.cows.8.txt)
[traceback bows and cows 9.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/11716058/traceback.bows.and.cows.9.txt)

**Comment by TRIDENT1313** [comment]
More game bugs...
Frankly, I'm too tired to give a shit now.
I'll update current release to fix poems stuff
Fixing games will be...
I dunno
But it won't be anytime soon
