### ISSUE TITLE
No music when using custom bgm

### ISSUE THREAD

**Issue by MarioXenobladefan614** [ForeverAndEverTeam/fae-mod#122]
Whenever I try to play a bgm I placed in the the custom bgm folder, no music plays and the bgm stays silent as if no music is playing.

**Comment by TRIDENT1313** [comment]
Known bug
It's because you're trying to play a file that isn't supported in it's encoding.
If you've converted it from one format to another without using a file converter, this can happen.
There are other causes too, but your problem is your files.
