### ISSUE TITLE
That nap sure will take long...

### ISSUE THREAD

**Issue by MonikaEndDie** [ForeverAndEverTeam/fae-mod#125]
one of the greetings seems to bug since i got this as soon i open the mod today:
```
I'm sorry, but an uncaught exception occurred.

While running game code:
ScriptError: could not find label 'fae_showpoem'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/core/script-ch30.rpyc", line 208, in script call
  File "game/core/script-ch30.rpyc", line 356, in script call
  File "game/dialogs/script-greetings.rpyc", line 290, in script call
  File "C:\Doki Doki Literature Club Sayori after story\renpy\ast.py", line 1705, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/core/script-ch30.rpyc", line 208, in script call
  File "game/core/script-ch30.rpyc", line 356, in script call
  File "game/dialogs/script-greetings.rpyc", line 290, in script call
  File "C:\Doki Doki Literature Club Sayori after story\renpy\script.py", line 927, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'fae_showpoem'.

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.3.22090809
Forever & Ever 0.2.1
Tue Jun 20 18:28:14 2023
```
by the name of the error, i assume the greeting is the one where sayori take a nap waiting for the player to return and it start with the poem "just taking a long nap, still alive" or something like that.

(btw, just want to tell you that we appreciate all the efforts you put to upgrade your mod, i know it can get tiring mostly when bugs seems keeping persisting and spreading, but you have our encouragements. Don't force yourself on something if you're really exhausted mentally, just take the time needed for a break, you can resume your project later. We believe in you.)

**Comment by TRIDENT1313** [comment]
Extract this, shove the rpyc into the dialogs folder and hit replace.
Should fix the problem
[script-greetings.zip](https://github.com/ForeverAndEverTeam/fae-mod/files/11818746/script-greetings.zip)

**Comment by MonikaEndDie** [comment]
Allright, it's done. I notice however that the new file is a bit lighter that the former (1ko), does the greeting has been fixed or simply delected? Not sure if i want to test my luck (and abusing my cinnamon bun) by restarting the mod again and again to check wich case is true lol.

**Comment by TRIDENT1313** [comment]
It was fixed.
As for testing your luck...
Worst case scenario, another bug shows up.
There's nothing that'll break your save.
