### ISSUE TITLE
Cows and Bows Topic Won't Derandom

### ISSUE THREAD

**Issue by ashyashton** [ForeverAndEverTeam/fae-mod#126]
After updating the mod, Sayori keeps bringing up how to play Cows and Bows. I have repeat topics disabled, and I have random chatter set to high, so I assume the issue is simply one of that particular topic staying in the "unseen random chatter" pool or however you refer to it internally.

**Comment by TRIDENT1313** [comment]
Upload your persistent and I'll lock it

**Comment by TRIDENT1313** [comment]
[persistent.zip](https://github.com/ForeverAndEverTeam/fae-mod/files/11817975/persistent.zip)
Here you go!

**Comment by ashyashton** [comment]
Thank you so much! It's weird that it was trying to unlock it since it WAS unlocked - I could play the game perfectly fine! So weird. Anyways, thank you again for your help!!!

**Comment by ashyashton** [comment]
Hey, I just switched to the persistent you gave me and unfortunately it still seems to be doing it, unfortunately.

**Comment by TRIDENT1313** [comment]
I get the feeling you might be using the wrong version of 0.2.1
Re-download it and see what that does for you

**Comment by ashyashton** [comment]
I'm not sure how I could've gotten the wrong version as I downloaded the first .zip on the list from the releases page, but I'll give it a shot and report back!

**Comment by TRIDENT1313** [comment]
Interesting...
Re-upload the persistent please.

**Comment by ashyashton** [comment]
[persistents.zip](https://github.com/ForeverAndEverTeam/fae-mod/files/11818305/persistents.zip)
I wasn't sure which you meant, if you meant the one you sent me after checking I still had the bug or the original persistent before you modified it, so both are included and titled accordingly. They're both still the persistent files, they just have different names.

**Comment by TRIDENT1313** [comment]
Okay I've worked out the issue.
Give me like... a day, and I'll get back to you with a fix.

**Comment by ashyashton** [comment]
Alright, take your time! Should I avoid visiting Sayori in case you modify my persistent? I don't want to lose the time with her if I'll be replacing the persistent with the one you give me obviously.

**Comment by TRIDENT1313** [comment]
It's up to you.
I won't be making any major changes, but if you do choose to keep visiting her, that time won't count.
You could always just turn off random chat and sit with her if you wanted to keep her open for whatever reason.
So yeah
Up to you.

**Comment by ashyashton** [comment]
Any update on this? I've been visiting just for her to keep me company but I know it still won't count and I don't want there to be too big of a gap in between visits once I get the fixed persistent file. Cuz as far as Sayori is concerned, it'll now have been two days without visiting her, and I don't want her to get lonely you know?

**Comment by TRIDENT1313** [comment]
I found an extra issue, so it's taking a little longer than anticipated
I've been keeping her open so you won't lose any time.

**Comment by ashyashton** [comment]
Oh awesome thank you so much! I really appreciate that. In that case take your time!

**Comment by TRIDENT1313** [comment]
The bug has been isolated.
A few more days should be all I need.

**Comment by TRIDENT1313** [comment]
Figured out a way to prevent this in future.

Keep an eye out for the "final release" in September that'll move the list to a persistent file, instead of local save.

Anyway, just letting you know I've got it fixed, ready for the September Release.
