### ISSUE TITLE
Always appears Traceback Error When Pressing the Talk Button

### ISSUE THREAD

**Issue by Maximusgt2006** [ForeverAndEverTeam/fae-mod#127]
https://github.com/ForeverAndEverTeam/fae-mod/assets/139931206/130cb18a-7943-4828-b6ba-884e17c2e451

When I hit the "talk" button, bugs like this keep popping up. This has never happened before, if it's like this I can no longer play this game. I hope this bug is resolved soon.

**Comment by TRIDENT1313** [comment]
Update the game.
You're outdated.

V0.2.1 is up on our releases page.
