### ISSUE TITLE
how do you play games?

### ISSUE THREAD

**Issue by Mgfern** [ForeverAndEverTeam/fae-mod#132]
i cant play any of the games, idk if im doing something wrong but they just dont appear when i try to play them also idk if there is supposed to be music but there isnt as well. could someone please fix this? thanks in advance! i turned the persistent into a text file because for some reason i cant just drag it in

[persistent.txt](https://github.com/ForeverAndEverTeam/fae-mod/files/12324129/persistent.txt)

**Comment by Mgfern** [comment]
also upon further inspection most of the poems give me errors, and i cant tell sayori i love her idk what i did wrong

**Comment by TRIDENT1313** [comment]
This has already been noted
I have built a fix already, and it has been prepared for our "Final" release in September.

**Comment by Mgfern** [comment]
Oh, alright! Sounds good I'll keep an eye out for the update!
