### ISSUE TITLE
Game refuses to launch

### ISSUE THREAD

**Issue by ifitmakesyoushush** [ForeverAndEverTeam/fae-mod#134]
[code]
I'm sorry, but errors were detected in your script. Please correct the
errors listed below, and try again.

File "game/core/poetry.rpy", line 487: style property modal is not known.
    modal True
         ^

File "game/core/poetry.rpy", line 145: invalid syntax
            raise TypeError(f"poem must be a Poem instance, not {type(poem).__name__}")
                                                                                      ^
    

Ren'Py Version: Ren'Py 6.99.12.4.2187
[/code]

**Comment by TRIDENT1313** [comment]
> Ren'Py Version: Ren'Py 6.99.12.4.2187 [/code]

We don't use R6, we use R8.

Delete whatever install you have there, get a new copy of DDLC, install the mod into that.

**Comment by ifitmakesyoushush** [comment]
So, delete the DDLC files and redownload? I tried that already multiple times.

**Comment by ifitmakesyoushush** [comment]
> 

I tried that already. It's still not working. Any suggestions?

**Comment by TRIDENT1313** [comment]
It says 6.99 in the error.
It should say 8.0.3 or something close to that.
You've installed it incorrectly.
Please read the [install instructions](https://github.com/ForeverAndEverTeam/fae-mod/wiki/Installing-the-mod) and ensure you followed them correctly.

**Comment by ifitmakesyoushush** [comment]
Oh! I've been running the wrong .exe file. I feel a little dumb now. Sorry to bother!
