### ISSUE TITLE
Fixing Grammar and Typos

### ISSUE THREAD

**Issue by TheGooseman27** [ForeverAndEverTeam/fae-mod#35]
I love the mod, but there are a few issues with the text, so I'm going through and fixing them.
![S9FO7lT_d](https://user-images.githubusercontent.com/58607715/70350501-ddfe0680-1834-11ea-9177-f73934cc2a4c.jpg)

**Comment by Professor-JMO** [comment]
Hiya, @TheGooseman27 
   Sorry for the late response.
The mod would appreciate your efforts into correcting some of these mistakes 👍 

Are you able to make a PR ( Pull Request ) to apply some of these fixes?

**Comment by TheGooseman27** [comment]
I don't know what a pull request is; I don't use this site very often.

**Comment by Professor-JMO** [comment]
@TheGooseman27 
Ok- so a quick run down.
This is the `Pull Request` area. ➡️ https://github.com/AlexanDDOS/fae-mod/pulls
These are the `game` files relevant to the mod. ➡️ https://github.com/AlexanDDOS/fae-mod/tree/master/game
And this would be a solid starting point to fix any issues with the text ➡️ https://github.com/AlexanDDOS/fae-mod/blob/master/game/topics.rpy
⏫ This more specifically deals with the `Topics` in the mod.

If you've created your own _Fork_ for this mod you can then use this option.
( See example image. )
![Example 1](https://user-images.githubusercontent.com/43480604/73499193-0d3c7a00-4385-11ea-9ba2-d7d527974022.PNG)

You'll see this via the next page.
![Example 2](https://user-images.githubusercontent.com/43480604/73499280-5260ac00-4385-11ea-8e6f-d44f5443841a.PNG)

Then towards the bottom of the same page, you'll see this text box.
![Example 3](https://user-images.githubusercontent.com/43480604/73499381-9358c080-4385-11ea-8e6f-37be194ceda6.PNG)

This should set you in the right direction 👍
