### ISSUE TITLE
What is the Game Root File

### ISSUE THREAD

**Issue by AlasterEarle** [ForeverAndEverTeam/fae-mod#49]
So Yeah Sayori asked me to send my picture in her "Game Root File" but I don't know what she meant by that not to forget she also can't find the image of mine
![bandicam 2020-10-12 01-29-20-318](https://user-images.githubusercontent.com/72709445/95688799-60f8a600-0c2a-11eb-9def-4ed2838a1da1.jpg)

**Comment by arachobia** [comment]
I manged to get her to 'see' the picture by naming it "screenshot" and putting it in the folder you've put "my picture" in

**Comment by MonikaEndDie** [comment]
Thanks man, it worked for me.

**Comment by TRIDENT1313** [comment]
[Closing as resolved]
