### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by RaitoninguHikari** [ForeverAndEverTeam/fae-mod#52]
Hey, lately I've been making Brazilian Portuguese translations of DDLC mods, I wanted to know if I have the permission to translate this mod for the Brazilian community, of course with your due credit when the translation is released, and then, do I have permission?

**Comment by StephenHCE117** [comment]
Hi this is clifford, PR and producer lead of the revitalized F&E team, talking to you on behalf of the new writing team, we appreciate your enthusiasm but we would like you to hold of on any translation work until our next release as we will be rewriting a large portion of the dialog in the game.
you can find our repo of the next update here https://github.com/Forever-and-Ever-Dev-Team/fae-mod for updates you can find us on discord at https://discord.gg/ZqfEddFKux

**Comment by RaitoninguHikari** [comment]
Okay, I'm happy to know that the mod hasn't been completely forgotten, for having a good time without any information and I'm a little worried, thank you.

**Comment by StephenHCE117** [comment]
also like to inform you that the translation process has changed and your invited to be part of the team to work hands on with the team if you wish
https://github.com/Forever-and-Ever-Dev-Team/fae-mod/wiki/Translator-Guidelines

**Comment by RaitoninguHikari** [comment]
I appreciate the invitation, but the way I do it is different, but I am thinking of learning the way it is done in this mod, in this case I will let you know

**Comment by TRIDENT1313** [comment]
Probably not much point replying to this thread, but I'll do it anyway.
We don't support translations.
If you wish to make a translation, you may, however we will not provide tech support for it.
[Closing as resolved]
