### ISSUE TITLE
Sayori "date" conversation crashes the game

### ISSUE THREAD

**Issue by BrandiBlitz** [ForeverAndEverTeam/fae-mod#59]
Whenever sayori starts talking about a "first date", the game crashes![image](https://user-images.githubusercontent.com/101225938/164115313-2a17a23b-a1ea-4c0f-b881-3bbe2f0ed8c7.jpeg)

**Comment by BrandiBlitz** [comment]
![image](https://user-images.githubusercontent.com/101225938/164115506-d0472843-4f76-469c-a035-e25c7cd92a0e.jpeg)

![image](https://user-images.githubusercontent.com/101225938/164115546-d6d01711-fe7a-4ecf-bc46-ca9dcdc7264d.jpeg)

**Comment by BrandiBlitz** [comment]
https://user-images.githubusercontent.com/101225938/164116022-13453adf-99f5-4f33-9353-0280008f1a8d.MOV

Also, the game tends to crash if I use the enter key to progress text.

**Comment by BrandiBlitz** [comment]
The workaround I have to do is to turn off "talk delay" all together. I hope you can find a way to fix this.

**Comment by BrandiBlitz** [comment]
I found the issue. It's the fact that 1, I was using "auto" to proceed text and 2, if I click to proceed text too fast, the game tends to crash. Specifically on the "first date" conversation. Also, it may also be an issue with other things for the other players.

**Comment by BrandiBlitz** [comment]
Suggestion: Please make Sayori repeat conversations on her own. Also, when will Submods be available?

**Comment by TRIDENT1313** [comment]
Probably should have mentioned this before labels got added, but anyway
We're working on a major update, which will eliminate these kinds of bugs.
Thank you for bringing this to our attention, however.

>Also, when will Submods be available?
Some point post-update, hopefully.
No promises though

>Suggestion: Please make Sayori repeat conversations on her own
I'm actually working on that right now!

>Please patch out the "exiting to main menu" feature. it crashes the game.

Good idea!
I don't know how I missed that one
Thank you!

**Comment by BrandiBlitz** [comment]
I'm happy to help any way I can~

**Comment by BrandiBlitz** [comment]
Heya again~

Suggestion: Add dialogue reaction when the player quits the game without saying goodbye.

Question: how will the affection progression system work?

**Comment by TRIDENT1313** [comment]
>Suggestion: Add dialogue reaction when the player quits the game without saying goodbye and when the game crashes.

It's actually in my notes of stuff to add, so it will be a thing

>Suggestion: Add an Apology option for when the player force quits & when the game crash

Again,  in my notes of stuff to add.


>Question: when will I be able to give Sayori a nickname?

YES!
That was the most requested feature when I was asking people what they wanted to see.
It'll happen!

>Question: how will the affection progression system work?

Not sure yet, I'm still working that one out.

>Question: how will outfits work for Sayori?

This will be a thing post-update.
Other outfits will require some extra framework
To answer your question, it'll most likely be the same as MAS, where you gift it, then select it.
But that's planned for a future update, not this one

**Comment by BrandiBlitz** [comment]
> But that's planned for a future update, not this one

That's reasonable

**Comment by TRIDENT1313** [comment]
[Closing as fixed]
