### ISSUE TITLE
[Suggestion] Notification Alerts

### ISSUE THREAD

**Issue by BrandiBlitz** [ForeverAndEverTeam/fae-mod#61]
Let Sayori Alert the player for conversations & reactions to certain websites (Windows-Reacts)

**Comment by TRIDENT1313** [comment]
>Let Sayori alert the player for conversations

I actually had that thought too.
I've spoken to the lead, who's given me the go-ahead to make that a thing.
So we will include that, hopefully in the new update



> Reactions to certain websites (Windows-Reacts)

This though...
I know other "Just (doki)" mods do this...
As of writing this, there are no plans to include this.
We may decide to include it later...
But for now, neither me, nor the lead, feel that window-reacts are worthwhile.

**Comment by TRIDENT1313** [comment]
[Closing as implemented]
