### ISSUE TITLE
Developer tools left inside

### ISSUE THREAD

**Issue by BrandiBlitz** [ForeverAndEverTeam/fae-mod#62]
![image](https://user-images.githubusercontent.com/101225938/173892157-c1ac683a-49d3-4671-9ffe-8741d300defa.jpeg)

The picture explains itself

**Comment by TRIDENT1313** [comment]
This has already been fixed.
Dev tools are no longer embedded in the game.

[Closing as resolved]

**Comment by BrandiBlitz** [comment]
But I had reinstalled this via github.
