### ISSUE TITLE
so something doesnt seem to be working on my end

### ISSUE THREAD

**Issue by GeoDoesThings** [ForeverAndEverTeam/fae-mod#63]
I'm completely unsure if i did this wrong, or if i installed it wrong somehow (using the mod manager, might be why) but uh

Whenever i attempt to put an image (mostly random crap to see if it'd do anything) in the root game folder for the face thing, nothing actually seems to happen. It just after a while defaults to i guess not being able to find it

either i installed it wrong or im putting it in the wrong place, or it's an unknown bug, hell if i know
i've tried putting said images in both the root game director and mod_assets, but still doesnt do anything

**Comment by TRIDENT1313** [comment]
The version of the mod you're playing is no longer supported, unfortunately.
That topic in particular has been removed in the upcoming update.
[Closing as wontfix]
