### ISSUE TITLE
中文字体问题导致报错崩溃（Chinese Font to CRASH GAME）

### ISSUE THREAD

**Issue by Marionic0723** [ForeverAndEverTeam/fae-mod#68]
看前文来说，好像是纱世里说到“莫妮卡有自己的声音，她们三个都没有，但是发现可以用Rep’PY合成”的时候，突然崩溃了。

![20221222115320_1](https://user-images.githubusercontent.com/76898556/209055116-dc7c000e-7aab-409e-8103-dc86a5e9e28e.jpg)

ERROR LOG：
![20221222115410_1](https://user-images.githubusercontent.com/76898556/209054676-9716562c-e62c-4839-8500-19a85517f4bd.jpg)

I gently open the folder, mod_assets\fonts not have ChineseRobot.ttf,
So i copy to this folder.

![image](https://user-images.githubusercontent.com/76898556/209054915-515a775b-bd90-48d7-964e-2b7a20e52e46.png)

**Comment by TRIDENT1313** [comment]
Hi @Marionic0723 
Unfortunately, as this is an issue about the old version of the mod (which is very old and outdated), we don't provide support for it anymore.
Please see [here](https://github.com/ForeverAndEverTeam/fae-mod#reporting-bugs)
Regarding translations: In the new update, we decided to drop translation support.

There's a new update coming out very soon, so please be patient and feel free to make a new issue if you have any problems with the new version.
Thank you!

[Closing as wontfix]
