### ISSUE TITLE
[ BUG REPORT ] - Fatal exception on boot at night

### ISSUE THREAD

**Issue by Blizzardsev** [ForeverAndEverTeam/fae-mod#72]
# Overview:
As per title - the game runs into an error that I cannot ignore past.

## Replication steps:
Run the game during night; unsure if this is related.

## Additional information:
N/A

**Comment by Blizzardsev** [comment]
![image](https://user-images.githubusercontent.com/57731669/209452331-842087c0-cbc6-4847-b62a-05aa89bb481b.png)

**Comment by TRIDENT1313** [comment]
Hi, Blizzardsev!
Thanks for raising an issue!
This is actually a greeting bug that I actually thought I'd fixed already.
I've added to the list of stuff to be patched in the upcoming hotfix update.
