### ISSUE TITLE
Closing Game Results in Sayori Getting Hurt?

### ISSUE THREAD

**Issue by Waflarter** [ForeverAndEverTeam/fae-mod#73]
I had to go eat just now so I chose the option where you had to say bye because you had to eat but when I came back she was talking about how "it hurt" and "whatever I did to not do it again" which I know occurs when you force close the game.

https://user-images.githubusercontent.com/121370407/209457240-50841401-dafc-4923-968e-a278ac899167.mp4

**Comment by TRIDENT1313** [comment]
Thanks for raising an issue with us!
It seems like something's causing the mod to assign a weird greeting.
That's not supposed to happen.
Will add to the to-fix list.
