### ISSUE TITLE
music feature

### ISSUE THREAD

**Issue by MonikaEndDie** [ForeverAndEverTeam/fae-mod#75]
Hello! So 1st of all: congratulation for the brand new release of the mod! I was waiting for it since a moment and now, we can properly spend time with the 4 best vn girls. 2nd: just to be sure, do the missed music feature explanation bug at the intro even is why we can't use this feature for now, or it is unlocked by one of the topics? And if it's because of the bug, will we need to reset Sayori's memory to unlock the feature properly? And 3rd: happy holidays to you guys and thanks for the wonderfull present that Sayori (and the 3 others dokies) is.

**Comment by TRIDENT1313** [comment]
>  do the missed music feature explanation bug at the intro even is why we can't use this feature for now, or it is unlocked by one of the topics?

It's unlocked by a topic.
We'll be removing the line in the intro in the upcoming hotfix patch!
[Closing as resolved]
