### ISSUE TITLE
TBR [ FEATURE REQUEST ] - Anti text-skip

### ISSUE THREAD

**Issue by Blizzardsev** [ForeverAndEverTeam/fae-mod#77]
# Overview:
Currently, it is easy to skip dialogue as there is no prevention of the click action skipping to the end of the line, or starting the next one.

It'd be great to have a means of ensuring text completes so players don't risk missing dialogue, or have to go back to the History to check what was missed!

## Must haves:
- Measures to prevent text skipping: JN and MAS both have an implementation of this that can be adapted with credit!

## Could haves:
N/A

## Is this feature request related to a problem? Please describe.
Not a bug per se, but would improve the chat experience! It'd also mean writing is more appreciated.

**Comment by Blizzardsev** [comment]
A toggle is an option of course.

**Comment by TRIDENT1313** [comment]
I've been thinking about this issue for a long time now.
I'm still in two minds
On one hand I can see why it's nice to skip through text you've already seen, but then Blizz's point about appreciating writing also makes sense.

~~Also there's the fact we don't need any more borrowed code than we already have.~~

Toggling on/off is an option if this ever gets added, and probably quite a good one.
I'm not sure how to proceed here.
I'll give it some more thought.

**Comment by ashyashton** [comment]
I can definitely appreciate the point about appreciating writing. But on the other hand, if you have to FORCE someone to read the writing, they probably aren't appreciating it anyways, and you're just annoying the end user in that case. I agree the work SHOULD be appreciated, but making it unskippable will achieve that about as well as taping someone's eyes open and holding a book open in front of them imo

**Comment by TRIDENT1313** [comment]
I've made a decision on this.
It won't be added.
Given the circumstances around the mod currently, and that work is currently in full swing on a bugless release for a "final" 1.0, I don't think this is worth it.

[Closing as won't add]
