### ISSUE TITLE
Reversi Not Working

### ISSUE THREAD

**Issue by Waflarter** [ForeverAndEverTeam/fae-mod#80]
So I finally unlocked my first game to play with Sayori which is Reversi but uhh...

![image_2022-12-27_002523297](https://user-images.githubusercontent.com/121370407/209567523-05e6315b-cda0-4baa-b392-ab298dcbfc2a.png)

Yeah... Also, can you make Sayori say your name instead of saying "Hey player!" when she introduces the games cuz it kinda breaks the immersion.

**Comment by Waflarter** [comment]
Also, just a suggestion, you should add the default music into the "Music" section of the mod.

**Comment by TRIDENT1313** [comment]
Hi @Waflarter 
Thanks for raising this issue!
Minigames have always been a bit broken, we're doing our best to fix them.
I've added both to my to-fix list.

In future, please put suggestions into separate issues, otherwise it's impossible to keep track of things!
