### ISSUE TITLE
(oh god) Kissing Sayori Doesn't Work?

### ISSUE THREAD

**Issue by Waflarter** [ForeverAndEverTeam/fae-mod#81]
I offered to give Sayori a goodnight kiss and uhh...

![image_2022-12-27_012321757](https://user-images.githubusercontent.com/121370407/209571401-f6ad2051-f5ca-4fbe-828a-16cb2b47a0c8.png)

I think I broke her...

**Comment by Waflarter** [comment]
After that, a black screen with a dialogue box saying "Chu~" appeared (probably what the kiss supposed to sound like) and then after that a text thing at the bottom saying "Image "sayori" not found" and then (I SWEAR IM NOT ON SOMETHING) Sayori flew to the top of the screen and then she disappeared. After that, she said, "Sweet dreams, {my name}" in which the game closed.

**Comment by TRIDENT1313** [comment]
Hi @Warflarter
Thanks for raising this issue with us
Can you please attach a copy of your persistent file so I can investigate this issue?
Thanks in advance!

**Comment by Waflarter** [comment]
[persistent.zip](https://github.com/ForeverAndEverTeam/fae-mod/files/10306982/persistent.zip)

**Comment by TRIDENT1313** [comment]
Thank you!
Please delete your persistent and download the new update
It means you'll start from scratch, but you'll have a better player experience after all.
My apologies
[closing as fixed]
