### ISSUE TITLE
Gifting STILL Isn't Working?

### ISSUE THREAD

**Issue by Waflarter** [ForeverAndEverTeam/fae-mod#82]
I don't know if it's just me being stupid or it's the game's problem but I've dug into how the gifting feature works and correct me if I'm wrong but the game checks if you have a certain file and then executes a function depending on the file that's in the gifts folder.

However, knowing that one of the gifts is called "otter.gift", I inserted it into the gifts folder.

![image](https://user-images.githubusercontent.com/121370407/209699578-faf3844f-08dc-4d75-965d-1f171126f460.png)

However, when I asked Sayori to check for gifts, she still said that there wasn't anything there...?

![image](https://user-images.githubusercontent.com/121370407/209699878-e175e441-658c-4a85-a664-c1341036d5c0.png)

**Comment by TRIDENT1313** [comment]
Couple of things.
1. Don't use OneDrive
2. Gifting has always been a bit fucky, so I'm looking into fixing it in the upcoming update.
