### ISSUE TITLE
the game has an exeption occure when i try to add new music or give a gift

### ISSUE THREAD

**Issue by gasterikuri** [ForeverAndEverTeam/fae-mod#86]
the game wont allow me to give gifts or add music it has a execption occured error come up when i try to do ethier of those 
![image_2023-01-02_184046965](https://user-images.githubusercontent.com/112905896/210285195-d3ba624a-0f80-4af8-b6b3-44e7c625eca5.png)

**Comment by TRIDENT1313** [comment]
Yeah this can happen.
It's been noted for fixing in a future update.
