### ISSUE TITLE
[ TYPOS ] 

### ISSUE THREAD

**Issue by wowm03** [ForeverAndEverTeam/fae-mod#87]
### Topic: Do you think about MC?
issue: "And come to think of it... did _**I even**_ have a family?..." 

![image](https://user-images.githubusercontent.com/90627231/210726987-532924cc-2094-42a3-a61d-858f7a1358a6.png)

**Comment by wowm03** [comment]
![image](https://user-images.githubusercontent.com/90627231/210924559-600d40e0-28ab-47bd-9b1e-dea637298c5e.png)

lack of spaces between punctuation marks

**Comment by wowm03** [comment]
### Topic: Liking Flowers
issue: space after comma/space before "ehehehe~"

![image](https://user-images.githubusercontent.com/90627231/211155122-267138c3-655c-48e9-a7d5-4d5b034c98e5.png)

**Comment by TRIDENT1313** [comment]
This has been noted and we're fixing it in the next update.
