### ISSUE TITLE
Unable to play games with Sayori again after closing the mod

### ISSUE THREAD

**Issue by MarioXenobladefan614** [ForeverAndEverTeam/fae-mod#88]
Sayori introduced reversi and bows and cows to me which allowed me to play but after closing the mod and then opening it back up, I'm no longer able to play these games as the options in the play tab have disappeared like she never introduced them to me.
![Screenshot (13)](https://user-images.githubusercontent.com/122083188/210957393-f999c76c-9796-48d2-9a90-26ec87620a30.png)

**Comment by TRIDENT1313** [comment]
Please see #103
