### ISSUE TITLE
[ FEATURE REQUEST ].chr files easter egg...maybe?

### ISSUE THREAD

**Issue by UsamiRenko04** [ForeverAndEverTeam/fae-mod#90]
I do not exactly know if it would be ok to delete those .chr files since they exist...
So if someone's chr is deleted, could it possible for Sayori to make some reactions?
If there is such easter egg... Just ignore me. 

(But I hope sayori.chr doesn`t exist so it couldn't be deleted by mistake and then...)

**Comment by TRIDENT1313** [comment]
Interesting idea
We may do something like that in the future

**Comment by TRIDENT1313** [comment]
Unfortunately I don't see a path forward for this right now.

I'm currently hard at work for a bug-free 1.0 "final" release.

I don't see a point in adding easter eggs now.

[Closing as won't add]
