### ISSUE TITLE
I try to open the game but it wont run

### ISSUE THREAD

**Issue by childonsmiledip** [ForeverAndEverTeam/fae-mod#92]

**Comment by MonikaObsessed** [comment]
I keep getting: I'm sorry, but an uncaught exception occurred

While running game code:
  File "game/core/splash.rpy", line 13, in <module>
Exception: DDLC archive files not found in /game folder. Check your installation and try again. But there is no splash.rpy file

**Comment by TRIDENT1313** [comment]
Hello.
Please make sure you carefully follow the instructions [here](https://github.com/ForeverAndEverTeam/fae-mod/wiki/Installing-the-mod) to install the mod.

[Closing as resolved]
