### ISSUE TITLE
Discord doesn't work

### ISSUE THREAD

**Issue by ashyashton** [ForeverAndEverTeam/fae-mod#93]
I joined the Discord and there's just no channels. I can't see the rules, I can't find the entrance code, nothing. I'm in the "entrance code place" room except it seems to be locked so I can't access it. It's all just blank, with a "messages failed to load" banner at the bottom.

**Comment by ashyashton** [comment]
This STILL hasn't been fixed, and it seems a LOT of issues are being ignored. Is this project just dead or something?

**Comment by TRIDENT1313** [comment]
Closing as resolved
